pygowave_client/urls.py
#
# PyGoWave Server - The Python Google Wave Server
# Copyright 2009 Patrick Schneider <patrick.p2k.schneider@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.conf.urls.defaults import *

from pygowave_client.views import *

urlpatterns = patterns('',
	(r'^(?P<package>\w+)/(?P<module>\w+).js$', view_module),
	(r'^pygowave_client_combined.js$', view_combined),
)

pygowave_server/urls.py
#
# PyGoWave Server - The Python Google Wave Server
# Copyright 2009 Patrick Schneider <patrick.p2k.schneider@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.conf.urls.defaults import *

from pygowave_server.views import *
from pygowave_server.views import all_gadgets
from django.conf import settings as django_settings

urlpatterns = patterns('',
	(r'^$', index),
	(r'^home/$', home),
	(r'^settings/$', settings),
	(r'^waves/$', wave_list),
	(r'^waves/(?P<wave_id>\w+)/$', wave),
	(r'^gadgets/$', all_gadgets),
	(r'^gadgets/mine/$', my_gadgets),
	(r'^gadgets/load/$', gadget_loader),
	(r'^pycow/(?P<filename>\w+\.js)', pycow),
)

if 'rosetta' in django_settings.INSTALLED_APPS:
	urlpatterns += patterns('',
		url(r'^rosetta/', include('rosetta.urls')),
	)

urls.py
#
# PyGoWave Server - The Python Google Wave Server
# Copyright 2009 Patrick Schneider <patrick.p2k.schneider@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

from registration.views import register
from pygowave_server.forms import MyRegistrationForm

js_info_dict = {
    'packages': ('pygowave_client',),
}

urlpatterns = patterns('',
	(r'^admin/(.*)', admin.site.root),
	url(r'^accounts/register/$', register, name='registration_register', kwargs={
		"form_class": MyRegistrationForm,
		"backend": 'registration.backends.default.DefaultBackend'
	}),
	(r'^accounts/', include('registration.backends.default.urls')),
	(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
	(r'^i18n/', include('django.conf.urls.i18n')),
	(r'^client/', include('pygowave_client.urls')),
	(r'', include('pygowave_server.urls')),
)

pygowave_server/models.py
#
# PyGoWave Server - The Python Google Wave Server
# Copyright 2009 Patrick Schneider <patrick.p2k.schneider@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from datetime import datetime, timedelta

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.db import transaction
from django.core.exceptions import ObjectDoesNotExist
from django.utils.hashcompat import sha_constructor as sha1

from django.utils import simplejson

import uuid

from pygowave_server.utils import find_random_id, gen_random_id, datetime2milliseconds
from pygowave_server.common.operations import *

__author__ = "patrick.p2k.schneider@gmail.com"

ROOT_WAVELET_ID_SUFFIX = '!conv+root'

# Note: The term 'client' specifies all entities, that directly communicate
#       with this server by the means of a proprietary protocol.
#       Wave Foundation clients and servers will be treated sightly different,
#       but that is not implemented yet.
#
# BIG NOTE: All models represent local Waves at the moment - they will later
#           be extended to have a domain field which specifies external Waves.

class ParticipantManager(models.Manager):
	"""
	This class provides a method to determine the number of online users.
	
	"""
	
	def online_count(self):
		timeout = datetime.now() - timedelta(minutes=settings.ONLINE_TIMEOUT_MINUTES)
		return self.filter(last_contact__gte=timeout).count()
	
	def create_from_user(self, user):
		return self.create(
			id = "%s@%s" % (user.username, settings.WAVE_DOMAIN),
			name = user.username,
			user = user
		)

class Participant(models.Model):
	"""
	Represents participant information. It contains id, display name, avatar's
	URL, and an external URL to view the participant's profile page. The
	instances may be coming from external Wave servers (not yet).
	
	Note: This model also serves as user profile on this server.
	
	"""
	
	objects = ParticipantManager()
	
	id = models.CharField(max_length=255, primary_key=True)
	user = models.ForeignKey(User, blank=True, null=True, unique=True, related_name="participants")
	is_bot = models.BooleanField()
	last_contact = models.DateTimeField(auto_now_add=True)
	
	name = models.CharField(max_length=255, blank=True)
	avatar = models.URLField(verify_exists=False, blank=True)
	profile = models.URLField(verify_exists=False, blank=True)
	
	def create_new_connection(self):
		"""
		Creates a new connection object for this participant and returns it.
		This generates the participant's new access keys.
		
		"""
		new_conn = ParticipantConn(participant=self)
		new_conn.save()
		return new_conn
	
	def serialize(self):
		"""
		Serialize participant into Google's format (taken from Gadgets API).
		
		"""
		return {
			"id": self.id,
			"displayName": self.name,
			"thumbnailUrl": self.avatar,
			"profileUrl": self.profile,
			"isBot": self.is_bot
		}
	
	def __unicode__(self):
		return u"Participant '%s'" % (self.id)

class ParticipantConn(models.Model):
	"""
	Represents a particular connection from the wave server to the wave client.
	Holds wave access keys. These access keys are only valid for one connection.
	However, they are valid for multiple open wavelets on that connection.
	
	"""
	
	participant = models.ForeignKey(Participant, related_name="connections")
	created = models.DateTimeField(auto_now_add=True)
	last_contact = models.DateTimeField(auto_now_add=True)
	rx_key = models.CharField(max_length=42)
	tx_key = models.CharField(max_length=42)
	
	def save(self, force_insert=False, force_update=False):
		if not self.id:
			self.rx_key, self.tx_key = self.find_random_keys()
			super(ParticipantConn, self).save(True)
		else:
			super(ParticipantConn, self).save(force_insert, force_update)
	
	@classmethod
	def find_random_keys(cls):
		rx_key = str(uuid.uuid1())
		while cls.objects.filter(rx_key=rx_key).count() > 0:
			rx_key = str(uuid.uuid1()) # Should never happen, but just in case :)
		tx_key = str(uuid.uuid1())
		while cls.objects.filter(tx_key=tx_key).count() > 0:
			tx_key = str(uuid.uuid1())
		return rx_key, tx_key
	
	def __unicode__(self):
		return u"ParticipantConn '%s/%d'" % (self.participant.id, self.id)
	
	class Meta:
		verbose_name = _('participant connection')
		verbose_name_plural = _('participant connections')

class WaveManager(models.Manager):
	
	@transaction.commit_on_success
	def create_and_init_new_wave(self, creator, title):
		wave = self.create()
		
		wavelet = Wavelet(wave=wave, creator=creator, title=title, is_root=True)
		wavelet.save()
		wavelet.participants.add(creator)
		
		blip = Blip(wavelet=wavelet, creator=creator)
		blip.save()
		wavelet.root_blip = blip
		wavelet.save()
		return wave

class Wave(models.Model):
	"""
	Models wave instances. These are the core of Google Wave.
	A single wave is composed of its id and any wavelets that belong to it.
	
	"""
	
	objects = WaveManager()
	
	id = models.CharField(max_length=42, primary_key=True) # Don't panic :P
	
	def root_wavelet(self):
		return self.wavelets.get(is_root=True)
	
	def save(self, force_insert=False, force_update=False):
		if not self.id:
			self.id = find_random_id(Wave.objects, 10)
			super(Wave, self).save(True)
		else:
			super(Wave, self).save(force_insert, force_update)
	
	def create_wavelet(self, creator, title):
		wavelet = Wavelet(wave=self, creator=creator, title=title, is_root=False)
		wavelet.save()
		wavelet.participants.add(creator)
		
		blip = Blip(wavelet=wavelet, creator=creator)
		blip.save()
		wavelet.root_blip = blip
		wavelet.save()
		return wavelet
	
	def __unicode__(self):
		return u"Wave %s" % (self.id)

class Wavelet(models.Model):
	"""
	A wavlet within a wave. Wavelets have an id, exactly one creator and one
	root blip, a creation date/time and a last modified date/time, a title,
	a version, zero or more participants, data documents which serve as
	free-form metadata and (potentially) a lot of blips.
	
	"""
	
	id = models.CharField(max_length=42, primary_key=True)
	wave = models.ForeignKey(Wave, related_name="wavelets")
	creator = models.ForeignKey(Participant, related_name="created_wavelets")
	is_root = models.BooleanField()
	root_blip = models.OneToOneField("Blip", related_name="rootblip_wavelet", null=True)
	created = models.DateTimeField(auto_now_add=True)
	last_modified = models.DateTimeField(auto_now=True)
	title = models.CharField(max_length=255, blank=True)
	version = models.IntegerField(default=0)
	participants = models.ManyToManyField(Participant, related_name="wavelets")
	participant_conns = models.ManyToManyField(ParticipantConn, blank=True, related_name="wavelets", verbose_name=_(u'connections'))
	
	def blipById(self, id):
		"""
		Returns the Blip object with the given id, if the Blip resides on this
		Wavelet. Returns None otherwise.
		
		"""
		
		try:
			return self.blips.get(id=id)
		except ObjectDoesNotExist:
			return None
	
	def save(self, force_insert=False, force_update=False):
		if not self.id:
			if self.is_root:
				self.id = self.wave.id + ROOT_WAVELET_ID_SUFFIX
			else:
				self.id = find_random_id(Wavelet.objects, 10, prefix=self.wave.id+"!")
			super(Wavelet, self).save(True)
		else:
			super(Wavelet, self).save(force_insert, force_update)
	
	def creationTimeMs(self):
		"""
		Returns the time of creation of this Wavelet in milliseconds since
		the epoc.
		
		"""
		return datetime2milliseconds(self.created)
	
	def lastModifiedTimeMs(self):
		"""
		Returns the last modified time of this Wavelet in milliseconds since
		the epoc.
		
		"""
		return datetime2milliseconds(self.last_modified)
	
	def __unicode__(self):
		return u"Wavelet '%s' (%s)" % (self.title, self.id)
	
	def serialize(self):
		"""
		Serialize the wavelet into a format that is compatible with robots and
		the client.
		
		"""
		return {
			"rootBlipId": getattr(self.root_blip, "id", None),
			"title": self.title,
			"creator": self.creator.id,
			"creationTime": self.creationTimeMs(),
			"dataDocuments": None, #TODO (is not declared in the robot protocol example)
			"waveletId": self.id,
			"participants": map(lambda p: p.id, self.participants.all()),
			"version": self.version,
			"lastModifiedTime": self.lastModifiedTimeMs(),
			"waveId": self.wave.id,
			"isRoot": self.is_root,
		}
	
	def serialize_blips(self):
		"""
		Serialize the wavelet's blips into a format that is compatible with
		robots and the client.
		
		"""
		blipmap = {}
		for blip in self.blips.order_by("created").all():
			blipmap[blip.id] = blip.serialize()
		return blipmap
	
	def applyOperations(self, ops, contributor):
		"""
		Apply the operations on the wavelet.
		Returns a dict for tempId->blipId mapping.
		
		Note: This may modify or even delete some operations.
		
		"""
		
		newBlips = {}
		
		i = 0
		while i < len(ops):
			op = ops[i]
			if op.blipId != "":
				blip = self.blipById(op.blipId)
				if blip == None:
					#TODO: error handling
					del ops[i]
					continue
				if op.type == DOCUMENT_DELETE:
					blip.deleteText(op.index, op.property, contributor)
				elif op.type == DOCUMENT_INSERT:
					blip.insertText(op.index, op.property, contributor)
				elif op.type == DOCUMENT_ELEMENT_DELETE:
					blip.deleteElement(op.index, contributor)
				elif op.type == DOCUMENT_ELEMENT_INSERT:
					blip.insertElement(op.index, op.property["type"], op.property["properties"], contributor)
				elif op.type == DOCUMENT_ELEMENT_DELTA:
					try:

pygowave_server/templates/pygowave_server/gadgets/all_gadgets.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load pgw_nav %}

{% block title %}{% trans "All Gadgets" %}{% endblock %}
{% block nav %}{% pgw_navbar "gadgets" "all_gadgets" %}{% endblock %}

{% block content %}
<div class="section">
	{% if gadgets %}
		{% trans "Hover over a Gadget's title to see its description." %}
		<table>
			<tr><th>{% trans "Title" %}</th><th>{% trans "Uploaded by" %}</th><th>{% trans "Download" %}</th></tr>
		{% for gadget in gadgets %}
			<tr>
				<td class="gadget_title" title="{{ gadget.description|escape }}">{{ gadget.title|escape }}</td>
				<td>{{ gadget.by_user }}</td>
				<td>
					<a href="{{ gadget.url }}"><img src="{{ MEDIA_URL }}images/download.png" width="16" height="16" title="{% trans "Download" %}" alt="{% trans "Download" %}" /></a>
				</td>
			</tr>
		{% endfor %}
		</table>
		<script type="text/javascript">
			new Tips($$(".gadget_title"), {className: 'tooltip'});
		</script>
	{% else %}
	{% trans "No one has submitted any Gadget. Sigh." %}
	{% endif %}
</div>
{% endblock %}

pygowave_server/templates/pygowave_server/gadgets/gadget_error.html
{% extends "pygowave_server/gadgets/gadget_wrapper.html" %}
{% load i18n %}
{% block title %}{% trans "Gadget Loader Error" %}{% endblock %}
{% block additional_header %}
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/style.css" type="text/css" />
{% endblock %}
{% block content %}
<div class="gadget_loader_fail">
	<div class="msg_div">
{% trans "Error while loading Gadget:" %}<br/>
{{ error_message }}
	</div>
	<div class="bg_div" />
</div>
{% endblock %}

pygowave_server/templates/pygowave_server/gadgets/gadget_wrapper.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>{% block title %}{{ gadget.title }}{% endblock %}</title>
	<style type="text/css">html,body{height:100%;width:100%;margin:0;padding:0;}</style>
	<script type="text/javascript" src="{{ wrapper_script_url }}"></script>{% if gadget.features.wave_preview %}
	<script type="text/javascript" src="http://wave-api.appspot.com/public/wave.js"></script>{% endif %}
	<script type="text/javascript">
		__MODULE_ID__ = {% if gadget_id %}{{ gadget_id }}{% else %}null{% endif %};
		gadgets._urlParameters = {% if url_parameters %}{{ url_parameters|safe }}{% else %}{}{% endif %};
		gadgets._prefs = {% if gadget %}{{ gadget.prefs_json|safe }}{% else %}null{% endif %};
		gadgets._lang = "{{ LANGUAGE_CODE|slice:":2"|upper }}";
	</script>
{% block additional_header %}{% endblock %}
</head>

<body>
{% block content %}
{{ gadget.content|safe }}
{% endblock %}
</body>

</html>

pygowave_server/templates/pygowave_server/gadgets/my_gadgets.html
{% extends "base.html" %}
{% load i18n %}
{% load pgw_nav %}

{% block title %}{% trans "My Gadgets" %}{% endblock %}
{% block nav %}{% pgw_navbar "gadgets" "my_gadgets" %}{% endblock %}

{% block content %}
{% if not duplicate %}
<h4>{% trans "Manage my Gadgets" %}</h4>
<div class="section">
	{% if gadget_registered %}<span class="success_message">{% trans "Your Gadget was successfully registered." %}</span><br/>{% endif %}
	{% if my_gadgets %}
		{% trans "Hover over a Gadget's title to see its description." %}
		<table>
		{% for gadget in my_gadgets %}
			<tr>
				<th class="gadget_title" title="{{ gadget.description|escape }}">{{ gadget.title|escape }}</th>
				<td>
					<a href="{{ gadget.url }}"><img src="{{ MEDIA_URL }}images/download.png" width="16" height="16" title="{% trans "Download" %}" alt="{% trans "Download" %}" /></a>&nbsp;
					<a href="javascript:confirmDelete({{ gadget.id }},'{{ gadget.title|escapejs }}');"><img src="{{ MEDIA_URL }}images/edit-delete.png" width="16" height="16" title="{% trans "Delete" %}" alt="{% trans "Delete" %}" /></a>
				</td>
			</tr>
		{% endfor %}
		</table>
		<script type="text/javascript">
			new Tips($$(".gadget_title"), {className: 'tooltip'});
			
			function confirmDelete(id, title) {
				if (confirm("{% trans 'Do you really want to delete \"%s\"?' %}".replace("%s", title)))
					window.location = "?delete=" + id;
			}
		</script>
	{% else %}
	{% trans "You didn't submit any Gadgets. Use the form below to add one." %}
	{% endif %}
</div>
{% endif %}
<h4>{% trans "Add or upload new Gadget" %}</h4>
<div class="section">
	{% if not duplicate %}
	<form method="post" action="{% url pygowave_server.views.my_gadgets %}" enctype="multipart/form-data" class="gadget_form">
		<table>
			<tr><td colspan="2">
				{{ form.external }}
				<div id="ext_selector">
					<ul>
						<li><a href="#ext_selector-0">{% trans "Upload" %}</a></li>
						<li><a href="#ext_selector-1">{% trans "External URL" %}</a></li>
					</ul>
					<div id="ext_selector-0">
						{{ form.non_field_errors }}{{ form.upload.errors }}
						{{ form.upload }}
					</div>
					<div id="ext_selector-1">
						{{ form.non_field_errors }}{{ form.url.errors }}
						{{ form.url }}
					</div>
				</div>
				<script type="text/javascript">
					(function () {
						// Switched to MooTools - looks fine too
						MochaUI.tabify('ext_selector', function (index) {
							$("id_external").set("value", index);
						});
						
						// Keep the selected tab
						{% if form.upload.errors %}MochaUI.tabSelect("ext_selector", 0);
						{% else %}{% if form.url.errors %}MochaUI.tabSelect("ext_selector", 1);
						{% else %}MochaUI.tabSelect("ext_selector", parseInt($("id_external").get("value")));{% endif %}{% endif %}
					})();
				</script>
			</td></tr>
			<tr><th><label for="id_title">{{ form.title.label }}:</label></th><td>
				{{ form.title }}
				<script type="text/javascript">
					(function () {
						// Default title
						var default_title = "{% trans "(From Gadget header)" %}";
						$("id_title").addEvent('focus', function () {
							var elt = $("id_title");
							if (elt.get("value") == default_title) {
								elt.set("value", "");
								elt.removeClass("default_title");
							}
						}).addEvent('blur', function () {
							var elt = $("id_title");
							if (elt.get("value") == "") {
								elt.set("value", default_title);
								elt.addClass("default_title");
							}
						}).fireEvent('blur');
						$$(".gadget_form").addEvent("submit", function () {
							var elt = $("id_title");
							if (elt.get("value") == default_title)
								elt.set("value", "");
						});
					})();
				</script>
			</td></tr>
			<tr><th><label for="id_description">{{ form.description.label }}:</label></th><td>{{ form.description }}</td></tr>
			<tr><td class="submit_td" colspan="2"><input type="submit" value="{% trans "Submit" %}" /></td></tr>
		</table>
	</form>
	{% else %}
	<form method="post" action="{% url pygowave_server.views.my_gadgets %}?duplicate" enctype="multipart/form-data" class="gadget_form">
		<table>
			<tr><td colspan="2">
				{{ form.external }}{{ form.url }}{{ form.description }}
				<ul class="errorlist"><li>{% trans "A Gadget with this title already exists." %}</li></ul>
				{% if can_overwrite %}{% trans "You may change the title or leave it to overwrite the existing Gadget." %}{% else %}{% trans "Please enter a new title." %}{% endif %}
			</td></tr>
			<tr><th><label for="id_title">{{ form.title.label }}:</label></th><td>{{ form.title }}{{ form.title.errors }}</td></tr>
			<tr><td class="submit_td" colspan="2"><input type="submit" name="cancel" value="{% trans "Cancel" %}" /> <input type="submit" value="{% trans "Submit" %}" /></td></tr>
		</table>
	</form>
	{% endif %}
</div>
{% endblock %}